#define PROBLEM "https://yukicoder.me/problems/no/430"
#include "base.hpp"

/* #include <atcoder/all> */
/* using namespace atcoder; */
/* #include "expansion/ac-library/all.hpp" */
#include "string.hpp"

void solve(){
    string s; cin >> s;
    int m; cin >> m;
    ll ans = 0;
    Trie<char, 'A'> trie;
    REP(i, m) {
        string c; cin >> c;
        trie.add(c);
    }
    trie.build_failure();
    print(trie.aho_corasick(s));
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() {
    // Fasterize input/output script
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout << fixed << setprecision(100);
    // scanf/printf user should delete this fasterize input/output script

    int t = 1;
    //cin >> t; // comment out if solving multi testcase
    for(int testCase = 1;testCase <= t;++testCase){
        solve();
    }
    return 0;
}
