#define PROBLEM "https://onlinejudge.u-aizu.ac.jp/problems/ALDS1_14_B"
#include "general.hpp"

/* #include <atcoder/all> */
/* using namespace atcoder; */
/* #include "expansion/ac-library/all.hpp" */
#include "string.hpp"

void solve(){
    string t, p; cin >> t >> p;
    RollingHash<MI3> rh;
    auto hash_t = rh.build(t);
    auto hash_p = rh.build(p);
    int n = t.length(), m = p.length();
    REP(i, n-m+1) {
        if(rh.query(hash_t, i, i+m) == rh.query(hash_p, 0, m)) print(i);
    }
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() {
    // Fasterize input/output script
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout << fixed << setprecision(100);
    // scanf/printf user should delete this fasterize input/output script

    int t = 1;
    //cin >> t; // comment out if solving multi testcase
    for(int testCase = 1;testCase <= t;++testCase){
        solve();
    }
    return 0;
}
