#define PROBLEM "https://atcoder.jp/contests/abc185/tasks/abc185_f"
#include "general.hpp"

/* #include <atcoder/all> */
/* using namespace atcoder; */
/* #include "expansion/ac-library/all.hpp" */
#include "segtree.hpp"

void solve(){
    int n, q; cin >> n >> q;
    VI a(n); cin >> a;
    SegTree<int, internal_operator::default_xor, internal_operator::zero> seg(a);
    REP(i, q) {
        int t, x, y; cin >> t >> x >> y;
        if(t == 1) seg.set(x-1, seg[x-1] ^ y);
        else print(seg.prod(x-1, y));
    }
}

// generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
int main() {
    // Fasterize input/output script
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout << fixed << setprecision(100);
    // scanf/printf user should delete this fasterize input/output script

    int t = 1;
    //cin >> t; // comment out if solving multi testcase
    for(int testCase = 1;testCase <= t;++testCase){
        solve();
    }
    return 0;
}
